200:
  - PHP
  - Symfony
  - Doctrine
  - Swiftmailer
  - MySQL
  - HTML
  - HTML5
  - CSS
  - CSS3
  - XML
  - JavaScript
  - jQuery
  - YAML
  - OOP
  - Design Patterns
  - Symfony Components
  - Symfony Ecosystem
  - Ajax
  - git
  - Twig
  - Amazon Web Services
  - SQL
  - "*js"

190:
  - Assetic
  - Sass
  - GitHub
  - Bitbucket
  - EC2
  - Elastic Beanstalk
  - SES
  - RDS
  - Route 53
  - S3
  - Assetic

180:
  - PHPStorm
  - PHPExcel
  - DNS
  - Domains
  - Webhosting
  - LAMP
  - HTTP

170:
  - Ubuntu
  - Google APIs
  - Bootstrap
  - i18n
  - l10n
  - DevOps

160:
  - Scrum
  - jQueryUI
  - REST
  - Webservices
  - Twelve-Factor App
  - Ionic

150:
  - Vagrant
  - Apache
  - mPDF
  - Bash Scripting
  - WAMP
  - Unit Tests
  - Jekyll
  - phpspec
  - prophecy
  - OAuth
  - PHP League

140:
  - phpunit
  - Windows
  - Office
  - Travis CI
  - Jenkins
  - User Stories
  - Pimple
  - Responsive
  - Heroku
  - Mac
  - Docker
  - Beanstalkd
  - SVG
  - Apple
  - Behat
  - Mink
  - Guzzle
  - Xdebug

130:
  - DigitalOcean
  - RSS
  - Atom
  - Zend Framework
  - Composer
  - Packagist
  - Goutte
  - Gaufrette
  - VirtualBox
  - ElastiCache
  - SEO
  - jQuery Mobile
  - Monolog
  - Social Media
  - Subversion
  - Chive
  - phpMyAdmin
  - Navicat
  - HeidSQL
  - Supervisor
  - Notepad++
  - Titanium
  - PhoneGap/Cordova
  - ngCordova
  - Ansible
  - nginx
  - BDD
  - TDD
  - Cynefin

120:
  - NoSQL
  - Postfix
  - Netbeans
  - Flash
  - Flex
  - Contao
  - Smarty
  - Less
  - CoffeeScript
  - Photoshop
  - Hardware
  - ExtJS
  - Android
  - XML-RPC
  - Nagios
  - Putty
  - duplicity

110:
  - MongoDB
  - Java
  - CQ5
  - WordPress
  - Node.js
  - Puppet
  - Chef
  - Soap
  - bind
  - SQS
  - SNS
  - VPN
  - iPhone
  - DDD

100:
  - Python
  - CQ5
  - PSR
  - Typo3
  - dojo
  - Action Script
  - Zend Studio
  - Hexagonal Architecture

90:
  - Redis
  - Backbone.js

#80:

