200:
  - PHP
  - Symfony
  - Doctrine
  - Swiftmailer
  - MySQL
  - HTML
  - HTML5
  - CSS
  - CSS3
  - XML
  - JavaScript
  - jQuery
  - YAML
  - OOP
  - Design Patterns
  - Symfony Components
  - Symfony Ecosystem
  - Ajax
  - git
  - Twig
  - Amazon Web Services
  - SQL

190:
  - Assetic
  - Sass
  - GitHub
  - Bitbucket
  - EC2
  - Elastic Beanstalk
  - SES
  - RDS
  - Route 53
  - S3
  - Assetic

180:
  - PHPStorm
  - PHPExcel
  - DNS
  - Domains
  - Webhosting
  - LAMP
  - HTTP

170:
  - Ubuntu
  - Google APIs
  - Twitter Bootstrap
  - i18n
  - l10n

160:
  - Scrum
  - jQueryUI
  - REST
  - Webservices

150:
  - Apache
  - mPDF
  - Bash Scripting
  - WAMP
  - Unit Tests

140:
  - phpunit
  - Windows
  - Office
  - Travis CI
  - Jenkins
  - User Stories
  - Pimple

130:
  - RSS
  - Atom
  - Zend Framework
  - Composer
  - Packagist
  - Goutte
  - Gaufrette
  - VirtualBox
  - ElastiCache
  - SEO
  - jQuery Mobile
  - Monolog
  - Social Media
  - Subversion
  - Chive
  - phpMyAdmin
  - Navicat
  - HeidSQL
  - Notepad++


120:
  - NoSQL
  - Postfix
  - Apple
  - Netbeans
  - Flash
  - Flex
  - Contao
  - Smarty
  - Less
  - CoffeeScript
  - Phhotoshop
  - Hardware
  - ExtJS
  - Android
  - XML-RPC
  - Nagios
  - Putty
  - duplicity

110:
  - MongoDB
  - nginx
  - Java
  - CQ5
  - WordPress
  - Node.js
  - Puppet
  - Chef
  - Vagrant
  - Soap
  - bind
  - SQS
  - SNS
  - VPN
  - iPhone

100:
  - Python
  - CQ5
  - TDD
  - PSR
  - Typo3
  - dojo
  - Action Script
  - Zend Studio

90:
  - Redis
  - Backbone.js

80:
  - Behat
  - Mink
